version: "3.8"
services:

  web:
    image: mapio/di-app
    build: ../build
    ports:
      - "80:80"
    networks:
      - di-network

  redis:
    image: redis
    volumes:
      - di-data:/data
    deploy:
      placement:
        constraints: [node.role == manager]
    command: redis-server --appendonly yes
    networks:
      - di-network

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - di-network

  portainer:
    image: portainer/portainer
    depends_on:
      - agent
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    ports:
      - target: 8000 # ssh tunnel
        published: 8000
      - target: 9000
        published: 9000
    volumes:
      - type: volume
        source: portainer
        target: /data
    networks:
      - agent-network

  agent:
    image: portainer/agent
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /var/lib/docker/volumes
        target: /var/lib/docker/volumes
    networks:
      - agent-network

volumes:
  di-data:
  portainer:

networks:
  agent-network:
    driver: overlay
    attachable: true
  di-network: