version: "3.8"
services:

  web:
    image: mapio/di-app
    build: ../build
    ports:
      - "80:80"
    networks:
      - di-network

  redis:
    image: redis
    volumes:
      - di-data:/data
    command: redis-server --appendonly yes
    networks:
      - di-network

volumes:
  di-data:

networks:
  di-network:
